version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSOWRD=postgres
      - POSTGRES_DB=book
    ports:
      - "5432:5432"
  book-service:
    image: books-v1:latest
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/book
      - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
      - KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL=http://etcd:2379/health
    ports:
      - "8080:8080"
    depends_on:
      - postgres
