kumuluzee:
  name: interface-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:80
    http:
      port: 80
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://interface-db:5432/user
      username: postgres
      password: postgres
      pool:
        max-size: 20
  discovery:
    etcd:
      hosts: http://etcd:2379