kumuluzee:
  name: interface-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/UsersDS
      connection-url: jdbc:postgresql://localhost:5432/user
      username: postgres
      password: postgres
      pool:
        max-size: 20
  health:
    servlet:
      mapping: /health/*
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/UsersDS
      etcd-health-check:
        type: readiness
        connection-url: http://0.0.0.0:2379/health
  metrics:
    servlet:
      enabled: true
      mapping: /metrics/*
    web-instrumentation:
      - name: infoEndpoint
        url-pattern: /v1/info/*
  discovery:
    etcd:
      hosts: http://0.0.0.0:2379