version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSOWRD=postgres
      - POSTGRES_DB=comment
    ports:
      - "5433:5432"
  book-service:
    image: amakovec/rso-book-cafe-comments:1.0.0-SNAPSHOT-8.1
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/comment
    ports:
      - "8081:8081"
    depends_on:
      - postgres