kumuluzee:
  name: book-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/BooksDS
      connection-url: jdbc:postgresql://localhost:5432/book
      username: postgres
      password: postgres
      pool:
        max-size: 20
  health:
    servlet:
      mapping: /health/*
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/BooksDS
      etcd-health-check:
        type: readiness
        connection-url: http://localhost:2379/health
  metrics:
    servlet:
      enabled: true
      mapping: /metrics/*
    web-instrumentation:
      - name: booksEndpoint
        url-pattern: /v1/books/*
  discovery:
    cluster: bookcafe
    etcd:
      hosts: http://localhost:2379
  streaming:
    kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: group1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
