version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSOWRD=postgres
      - POSTGRES_DB=user
    ports:
      - "5434:5432"
  book-service:
    image: interface-v1:latest
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/user
    ports:
      - "8082:8082"
    depends_on:
      - postgres